In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
df.info

<bound method DataFrame.info of      sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]>

In [4]:
L=['sepal.length','sepal.width','petal.length','petal.width']
x=df[L]
y=df['variety']    

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
KNN=KNeighborsClassifier(n_neighbors=20)

In [19]:
KNN.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=20)

In [20]:
pre=KNN.predict(x_test)

In [21]:
print(pre)

['Setosa' 'Versicolor' 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor'
 'Virginica' 'Setosa' 'Virginica' 'Setosa' 'Virginica' 'Versicolor'
 'Virginica' 'Setosa' 'Setosa' 'Virginica' 'Setosa' 'Versicolor'
 'Virginica' 'Versicolor' 'Versicolor' 'Virginica' 'Virginica' 'Setosa'
 'Versicolor' 'Versicolor' 'Versicolor' 'Setosa' 'Virginica' 'Virginica']


In [22]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [23]:
print(accuracy_score(y_test,pre))

1.0


In [24]:
print(confusion_matrix(y_test,pre))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]


In [25]:
print(classification_report(y_test,pre))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       1.00      1.00      1.00        11
   Virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

