In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
df=pd.read_csv("iris.csv")

In [56]:
L=['sepal.length','sepal.width','petal.length','petal.width']
x=df[L]
y=df['variety']    

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [58]:
from sklearn.decomposition import PCA 

In [59]:
p=PCA(n_components=1) #create our own model & 1 means converting into 1D matrix

In [60]:
A=p.fit_transform(x_train) #it convert n column into 1D 

In [61]:
B=p.transform(x_test) #fit_transform & transform are same

In [62]:
print(x_train)

     sepal.length  sepal.width  petal.length  petal.width
95            5.7          3.0           4.2          1.2
88            5.6          3.0           4.1          1.3
0             5.1          3.5           1.4          0.2
46            5.1          3.8           1.6          0.2
11            4.8          3.4           1.6          0.2
..            ...          ...           ...          ...
22            4.6          3.6           1.0          0.2
75            6.6          3.0           4.4          1.4
137           6.4          3.1           5.5          1.8
15            5.7          4.4           1.5          0.4
99            5.7          2.8           4.1          1.3

[120 rows x 4 columns]


In [63]:
print(A)

[[ 0.38032191]
 [ 0.2955278 ]
 [-2.63821091]
 [-2.49273773]
 [-2.56506492]
 [ 0.57772808]
 [ 0.85524535]
 [-2.66636036]
 [ 0.97833394]
 [ 2.88439493]
 [ 0.69085794]
 [ 1.82880455]
 [-2.75438618]
 [ 0.97160691]
 [ 1.14185262]
 [-2.84035373]
 [-2.23612877]
 [-2.65658607]
 [ 1.39979448]
 [-2.16298278]
 [ 2.20969865]
 [ 1.9520846 ]
 [-2.36440023]
 [ 2.58293095]
 [ 0.31174238]
 [-0.12406076]
 [ 0.71092063]
 [-2.79767908]
 [-2.54397217]
 [-0.01819886]
 [ 0.68886571]
 [ 0.27902647]
 [ 0.09441504]
 [ 1.26494121]
 [ 1.13395216]
 [ 0.42534342]
 [-2.25483359]
 [ 0.9931888 ]
 [ 0.86168564]
 [-2.62574399]
 [-2.92988264]
 [ 0.63976687]
 [ 0.23451907]
 [ 0.93802226]
 [-2.54195496]
 [-2.49862099]
 [ 1.9548022 ]
 [-2.58154128]
 [-2.53926233]
 [-0.45501411]
 [ 1.21940375]
 [ 1.46738687]
 [ 1.25277713]
 [ 2.01983832]
 [ 2.17327801]
 [ 2.66202809]
 [ 0.18478773]
 [ 1.99675333]
 [ 3.11960644]
 [ 2.96295816]
 [-2.8356439 ]
 [ 2.21274592]
 [-2.51699615]
 [-2.68238865]
 [-2.60345283]
 [ 1.99309668]
 [ 1.50737

In [64]:
print(x_test)

     sepal.length  sepal.width  petal.length  petal.width
47            4.6          3.2           1.4          0.2
73            6.1          2.8           4.7          1.2
74            6.4          2.9           4.3          1.3
129           7.2          3.0           5.8          1.6
67            5.8          2.7           4.1          1.0
89            5.5          2.5           4.0          1.3
143           6.8          3.2           5.9          2.3
21            5.1          3.7           1.5          0.4
108           6.7          2.5           5.8          1.8
12            4.8          3.0           1.4          0.1
147           6.5          3.0           5.2          2.0
76            6.8          2.8           4.8          1.4
119           6.0          2.2           5.0          1.5
35            5.0          3.2           1.2          0.2
28            5.2          3.4           1.4          0.2
122           7.7          2.8           6.7          2.0
13            

In [65]:
print(B)

[[-2.79029272]
 [ 0.96802057]
 [ 0.76001946]
 [ 2.42986384]
 [ 0.2832222 ]
 [ 0.21731734]
 [ 2.61093703]
 [-2.49693345]
 [ 2.36782505]
 [-2.73835789]
 [ 1.81268098]
 [ 1.37553791]
 [ 1.35022446]
 [-2.81926097]
 [-2.59403317]
 [ 3.54137352]
 [-3.17315594]
 [ 1.08808688]
 [ 1.64088925]
 [-0.69627021]
 [ 1.32665034]
 [ 1.44074052]
 [ 1.85212392]
 [-2.26596576]
 [ 1.34551463]
 [-0.14025739]
 [-0.85421031]
 [-2.58932334]
 [ 2.39934958]
 [ 1.49098782]]


In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [75]:
KNN=KNeighaborsClassifier(n_neighbors=20)

In [76]:
KNN.fit(A,y_train)

KNeighborsClassifier(n_neighbors=20)

In [77]:
pre=KNN.predict(B)

In [78]:
print(pre)

['Setosa' 'Versicolor' 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor'
 'Virginica' 'Setosa' 'Virginica' 'Setosa' 'Virginica' 'Versicolor'
 'Versicolor' 'Setosa' 'Setosa' 'Virginica' 'Setosa' 'Versicolor'
 'Virginica' 'Versicolor' 'Versicolor' 'Virginica' 'Virginica' 'Setosa'
 'Versicolor' 'Versicolor' 'Versicolor' 'Setosa' 'Virginica' 'Virginica']


In [79]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [80]:
print(classification_report(y_test,pre))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       0.92      1.00      0.96        11
   Virginica       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [81]:
print(accuracy_score(y_test,pre))

0.9666666666666667


In [82]:
print(confusion_matrix(y_test,pre))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  1 10]]
