In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
L=['sepal.length','sepal.width','petal.length','petal.width']
x=df[L]
y=df['variety']    

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [5]:
from sklearn.naive_bayes import GaussianNB

In [6]:
p=GaussianNB()

In [7]:
p.fit(x_train,y_train)

GaussianNB()

In [14]:
pre=p.predict(x_test)

In [15]:
print(p)

GaussianNB()


In [16]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [17]:
print(classification_report(y_test,pre))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       0.85      1.00      0.92        11
   Virginica       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.95      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



In [18]:
print(accuracy_score(y_test,pre))

0.9333333333333333


In [19]:
print(confusion_matrix(y_test,pre))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  2  9]]
