In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [59]:
ds=pd.read_csv('Iris.csv')

In [60]:
ds.shape

(150, 6)

In [61]:
#ds.info

In [62]:
ds.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [63]:
L=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
x=df[L]
y=df['Species']

In [64]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.8,random_state=32)

In [65]:
model=DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [66]:
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [67]:
pre=model.predict(x_test)


In [68]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [69]:
print(accuracy_score(y_test,pre))

0.9166666666666666


In [70]:
print(confusion_matrix(y_test,pre))

[[41  0  0]
 [ 0 38  1]
 [ 0  9 31]]


In [71]:
print(classification_report(y_test,pre))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        41
Iris-versicolor       0.81      0.97      0.88        39
 Iris-virginica       0.97      0.78      0.86        40

       accuracy                           0.92       120
      macro avg       0.93      0.92      0.91       120
   weighted avg       0.93      0.92      0.92       120



In [74]:
from sklearn import tree

In [75]:
tree.plot_tree(ds,filled=True)

InvalidParameterError: The 'decision_tree' parameter of plot_tree must be an instance of 'sklearn.tree._classes.DecisionTreeClassifier' or an instance of 'sklearn.tree._classes.DecisionTreeRegressor'. Got       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns] instead.